config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #faqs
  resources :faqs, only:[:index,:show]

  #contacts
  get 'contacts/complete', :to=>'contacts#complete', as: 'complete_contacts'
  resources :contacts, only:[:index,:create]

  #intro
  get 'intro/company', :to=>'intro#company', as: 'intro_company'
  get 'intro/service', :to=>'intro#service', as: 'intro_service'
  get 'intro/program', :to=>'intro#program', as: 'intro_program'

  resources :programs
  resources :accounts
  resources :accounts_products
  resources :accounts_product_categories
  resources :product_categories
  resources :products
  resources :orders
  resources :reports
  resources :users

  devise_for :admins, :controllers => { :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get 'edit', :to => 'admins::Registrations#edit'
    get 'login', :to => 'admins::Sessions#new'
    get 'logout', :to=> 'admins::Sessions#destroy'
  end

  devise_for :users, :controllers => {:omniauth_callbacks=>'users/omniauth_callbacks', :sessions => "users/sessions",:registrations => "users/registrations",:passwords => "users/passwords"}, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get '/users', :to => 'users/registrations#index', :as => :user_root # Rails 3s
    get '/login', :to => 'users/sessions#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :faq_category, :autosave=>true
  has_one :faq_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :faq
  accepts_nested_attributes_for :faq_content, :allow_destroy => true
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show]

  def before_init
    super
    @title= t(:menu_faq)
    @page_itemtype='http://schema.org/QAPage'
  end
  # GET /faqs
  # GET /faqs.json
  def index
    @faq_categories = FaqCategory.all

    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      if @faq_categories[0]
        @categoryId=@faq_categories[0].id.to_i
      else
        @categoryId=nil
      end
    end

    @faqs = Faq.where(:faq_category_id=>@categoryId).order('id desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: {:faqs=>@faqs,:admin=>admin} }
    end
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
    @faq_categories = FaqCategory.all

    if(params[:id])
      @faq = Faq.find(params[:id])
    end

    @title=@faq.title
    @meta_description=@faq.faq_content.content

    if(params[:faq_category_id])
      @categoryId=params[:faq_category_id].to_i
    else
      @categoryId=@faq.faq_category_id
    end

    @faqs = Faq.where(:faq_category_id=>@categoryId).order('id desc').page(params[:page]).per(10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @faq.faq_content}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end
end

app/views/faqs/_index.html.erb
<% breadcrumb :faqs %>
<div id="faq_main" class="container">
	<div class="row">
		<div class="col-xs-12 col-md-offset-4 col-md-9 col-md-pull-1 col-xl-offset-0 col-xl-pull-0 col-xl-12">
			<h2 class="col-xs-12"><%=t(:faq,scope:[:activerecord,:models]) %></h2>
			<p class="hidden-xs col-xs-12 description"><%=raw t(:faq_description) %></p>
			<div class="col-xs-12">
				<article>
					<ol id="faqCategoryList">
						<% unless faq_categories.empty? %>
						<% faq_categories.each do |faq_category| %>
						<li <% if(categoryId==faq_category.id) %> class="on"<% end %>>
							<%= link_to truncate(faq_category.title,:length => 20),faqs_path(:faq_category_id=>faq_category.id),{:class=>'title'} %>
						</li>
						<% end %>
					<% else %>
						<li><%=t(:no_data) %></li>
						<% end %>
					</ol>
				</article>
				<article>
					<dl id="faqList">
						<% unless faqs.empty? %>
						<% faqs.each do |faq| %>
						<dt<% if faq %><% if faq.id==faq.id %> class="on"<% end %><% end %>>
							<%= link_to truncate(faq.title,:length => 80), faq_path(faq),{:class=>'title'} %>
						</dt>
						<% if(faq_content)%>
						<% if(faq_content.id==faq.id) %>
						<dd><%=simple_format(faq_content.faq_content.content) %></dd>
						<% end %>
						<% end %>
						<% end %>
					<% else %>
						<dt><%=t(:no_data)%></dt>
						<% end %>
					</dl>
				</article>
			</div>
			<div class="pagination">
				<%= paginate faqs %>
			</div>
		</div>
	</div>
</div>

app/views/faqs/index.html.erb
<% breadcrumb :faqs %>
<%= render 'index',:faq_categories=>@faq_categories, :faqs=>@faqs, :faq_content=>@faq, :categoryId=>@categoryId %>

app/views/faqs/show.html.erb
<% breadcrumb :faq,@faq %>
<%= render 'index',:faq_categories=>@faq_categories, :faqs=>@faqs, :faq_content=>@faq, :categoryId=>@categoryId %>