config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  #faqs
  resources :faqs, only:[:index,:show]

  #contacts
  get 'contacts/complete', :to=>'contacts#complete', as: 'complete_contacts'
  resources :contacts, only:[:index,:create]

  #intro
  get 'intro/company', :to=>'intro#company', as: 'intro_company'
  get 'intro/service', :to=>'intro#service', as: 'intro_service'
  get 'intro/program', :to=>'intro#program', as: 'intro_program'

  resources :programs
  resources :accounts
  resources :accounts_products
  resources :accounts_product_categories
  resources :product_categories
  resources :products
  resources :orders
  resources :reports
  resources :users

  devise_for :admins, :controllers => { :sessions => "admins/sessions",:registrations => "admins/registrations" }, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get 'edit', :to => 'admins::Registrations#edit'
    get 'login', :to => 'admins::Sessions#new'
    get 'logout', :to=> 'admins::Sessions#destroy'
  end

  devise_for :users, :controllers => {:omniauth_callbacks=>'users/omniauth_callbacks', :sessions => "users/sessions",:registrations => "users/registrations",:passwords => "users/passwords"}, :path_names =>  {:sign_up=>'new',:sign_in => 'login', :sign_out => 'logout'} do
    get '/users', :to => 'users/registrations#index', :as => :user_root # Rails 3s
    get '/login', :to => 'users/sessions#new'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  after_initialize :default_values
  belongs_to :account_category
  belongs_to :user, counter_cache: true
  has_many :accounts_orders, dependent: :destroy
  has_many :accounts_products, dependent: :destroy
  has_many :orders, :through => :accounts_orders
  has_many :products, :through => :accounts_products
  private

  def default_values
    self.transaction_date ||= Date.today
  end
end

app/models/accounts_order.rb
class AccountsOrder < ApplicationRecord
  belongs_to :account
  belongs_to :order
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :trackable, :validatable, :timeoutable

  validates_length_of :email, within: 4..40
  validates_uniqueness_of :email
  validates_length_of :name, within: 1..60
  validates_length_of :password, :within => 5..255

  has_many :roles_admin
  has_many :role, :through => :roles_admin

  def role?(role)
    return !!self.role.find_by_title(role)
  end

  def timeout_in
    1.day
  end
end

app/models/admin_ability.rb
class AdminAbility
  include CanCan::Ability
  def initialize(admin)
    if admin
      can :manage, :all
    else
      cannot :manage, :all
    end
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates_presence_of :title
  validates :contact_content, :presence => true
  has_one :contact_content, :foreign_key => :id, :dependent=>:destroy
  accepts_nested_attributes_for :contact_content, :allow_destroy => true
  delegate :content, :to => :contact_content, :prefix => true
end

app/models/faq.rb
class Faq < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :faq_category, :autosave=>true
  has_one :faq_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :faq
  accepts_nested_attributes_for :faq_content, :allow_destroy => true
end

app/models/faq_category.rb
class FaqCategory < ActiveRecord::Base
  validates_presence_of :title
  has_many :faq, :dependent=> :destroy
end

app/models/faq_content.rb
class FaqContent < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :faq, :foreign_key => :id, inverse_of: :faq_content
  accepts_nested_attributes_for :faq
end

app/models/notice.rb
class Notice < ActiveRecord::Base
  is_impressionable
  validates_presence_of :title
  belongs_to :user, :autosave=>true
  has_one :notice_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :notice
  accepts_nested_attributes_for :notice_content, :allow_destroy => true, :update_only => true

  def notice_content
    super || build_notice_content
  end
end

app/models/notice_content.rb
class NoticeContent < ActiveRecord::Base
  validates_presence_of :content
  belongs_to :notice, :foreign_key => :id, inverse_of: :notice_content
end

app/models/order.rb
class Order < ApplicationRecord
  after_initialize :default_values

  validates_presence_of :user_id,:price,:discount,:payment
  belongs_to :user, counter_cache: true
  has_many :accounts_orders, dependent: :destroy
  has_many :orders_products, dependent: :destroy
  has_many :products, :through => :orders_products
  has_many :accounts, :through => :accounts_orders
  accepts_nested_attributes_for :orders_products, :allow_destroy => true

  private

  def default_values
    self.transaction_date ||= Date.today
  end
end

app/models/product.rb
class Product < ApplicationRecord
  validates_presence_of :title
  belongs_to :product_category, counter_cache: true
  has_many :orders, :through => :orders_products
  has_one :product_picture, dependent: :destroy
  accepts_nested_attributes_for :product_picture, :allow_destroy => true
end

app/models/program.rb
class Program < ActiveRecord::Base
  is_impressionable
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  has_many :program_categories_programs
  has_many :program_categories, :through => :program_categories_programs
  has_many :program_links, :through => :program_categories_programs
  has_one :program_content, :foreign_key => :id, :dependent => :destroy
  accepts_nested_attributes_for :program_content, :allow_destroy => true
end

app/models/program_link.rb
class ProgramLink< ActiveRecord::Base
  validates_presence_of :program_id, :program_link_category_id
  validates :program_id, :numericality => { :only_integer => true }
  belongs_to :program_link_category
  belongs_to :program
end

app/models/propose.rb
class Propose < ActiveRecord::Base
  validates_presence_of :title
  belongs_to :user,:autosave=>true
end

app/models/report.rb
class Report < ActiveRecord::Base
  acts_as_votable
  is_impressionable
  validates_presence_of :title
  belongs_to :user, counter_cache: true
  belongs_to :report_category, counter_cache: true
  has_one :report_content, :foreign_key => :id, :dependent => :destroy, inverse_of: :report
  accepts_nested_attributes_for :report_content, :allow_destroy => true, :update_only => true

  def report_content
    super || build_report_content
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  validates_presence_of :title
  validates_length_of :title, :minimum => 4, :maximum => 60, :allow_blank => true
  belongs_to :user, :autosave=>true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag, :counter_cache => true
end

app/models/user.rb
class User < ActiveRecord::Base
  include OmniauthAttributesConcern
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  acts_as_voter
  acts_as_votable
  #acts_as_commentable
  validates_presence_of :name, :email, :description, :on => :create
  validates_length_of :email, :within => 4..255
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates_length_of :password, :within => 4..255, :allow_blank => true
  has_many :user_authorizations

  def self.create_from_omniauth(params)
    self.__send__(params.provider, params)
  end
end

app/models/user_ability.rb
class UserAbility
  include CanCan::Ability

  def initialize(user)
      cannot :manage, :all
      can :create, [User]
      can :manage, [User, Propose, Model, Report, Compliment] if user
  end
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <address class="col-12">
        670-31-01025
        <a href="https://www.sleepinglion.pe.kr" target="_blank"><%=t(:jedearoweb) %></a>
        &nbsp;&nbsp; CopyLeft. 2020, SL. All wrongs reserved.
      </address>
      <!-- <form action="" class="form-inline">
        <select name="locale" class="form-control">
          <option value="zh-CN"<% if I18n.locale.to_s=='zh-CN' %> selected="selected"<% end %>><%=t(:chineses) %></option>
          <option value="en"<% if I18n.locale.to_s=='en' %> selected="selected"<% end %>><%=t(:english) %></option>
          <option value="ko"<% if I18n.locale.to_s=='ko' %> selected="selected"<% end %>><%=t(:korean) %></option>
        </select>
        <input type="submit" class="btn" value="<%=t(:submit) %>" />
      </form> -->
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div class="row">
      <h1 class="col-12 col-lg-3">
        <%= link_to root_path do %>
          <span class="logo"><%= t(:service_name) %></span>
        <% end %>
      </h1>
      <nav class="col-12 col-lg-9">
        <ul class="nav nav-pills">
          <li class="sl-dropdown
            <% if params[:controller] == 'intro' %> active
            <% end %>">
            <%= link_to intro_company_path do %>
              <%= t(:menu_intro) %>
            <% end %>
            <ul class="sl-dropdown-menu intro_menu">
              <li
              <% if current_page?(intro_company_path) %> class="active"
              <% end %>><%= link_to t(:submenu_intro1), intro_company_path %></li>
              <li
              <% if current_page?(intro_service_path) %> class="active"
              <% end %>><%= link_to t(:submenu_intro2), intro_service_path %></li>
            </ul>
          </li>
          <li class="sl-dropdown
            <% if params[:controller] == 'programs' %> active
            <% end %>">
            <%= link_to programs_path do %>
              <%= t(:program,scope:[:activerecord,:models]) %>
            <% end %>
            <ul class="sl-dropdown-menu intro_menu">
              <li
                <% if current_page?(programs_path) %> class="active"
                <% end %>><%= link_to t(:program,scope:[:activerecord,:models]), programs_path %></li>
              <li
                <% if current_page?(reports_path) %> class="active"
                <% end %>><%= link_to t(:report,scope:[:activerecord,:models]), reports_path %></li>
            </ul>
          </li>
          <li class="sl-dropdown
            <% if params[:controller] == 'faqs' || params[:controller] == 'contacts' %> active
            <% end %>">
            <%= link_to faqs_path do %>
              <%= t(:menu_support) %>
            <% end %>
            <ul class="sl-dropdown-menu">
              <li
              <% if current_page?(faqs_path) %> class="active"
              <% end %>><%= link_to t(:menu_faq), faqs_path %></li>
              <li
              <% if current_page?(contacts_path) %> class="active"
              <% end %>><%= link_to t(:menu_contact), contacts_path %></li>
            </ul>
          </li>
          <% if user_signed_in? %>
            <li class="red
              <% if params[:controller] == 'orders' %> active
              <% end %>" data-turbolinks="false">
              <%= link_to new_order_path do %><%= t(:menu_order) %>
              <% end %>
            </li>
            <li class="blue
              <% if (params[:controller] == 'users' && (params['action'] == 'index' || params['action'] == 'bye' || params['action'] == 'edit')) || params[:controller] == 'reports' %> active
              <% end %>"><%= link_to users_path do %><%= t(:menu_my_page) %>
              <% end %></li>
          <% else %>
            <li class="red
              <% if params[:controller] == 'orders' %> active
              <% end %>" data-turbolinks="false">
              <%= link_to new_order_path do %><%= t(:menu_order) %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%=I18n.locale %>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="<%=t(:service_name)%>">
  <meta name="author" content="Sleeping-Lion">
  <%= stylesheet_link_tag "front/application", :media => "all", "data-turbolinks-track" => true %>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <!--[if IE]>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <![endif]-->
  <title><%=t(:service_name)%></title>
</head>
<body>
<%= render :partial => 'layouts/header' %>
<div id="mom">
  <div id="main">
    <div class="sub_main">
      <%= yield %>
    </div>
  </div>
</div>
<%= render :partial => 'layouts/footer' %>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"></div>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</body>
</html>